/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz1sistemasg2;

public class App {
    

    public static void main(String[] args) {
        
       

    }

    /*  Implemente una funcion llamada calcularValorHora que cumpla con las siguientes caracteristicas
        * Recibe: 
            - Una cadena de caracteres que representa el tipo de vehiculo (C, M o B)
            - Un entero que representa la cantidad de horas de permanencia
        * Retorna:
            - Un entero representando el valor total de las boletas
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    public static int calcularValorHora(String tipoVehiculo, int cantidadHoras){

        int valorNetoHora = 0;
        int valorAdicion = 0;

        switch (tipoVehiculo) {
            case "C":
                valorNetoHora = cantidadHoras * 5000;
                break;
            case "M":
                valorNetoHora = cantidadHoras * 3000;
                break;
            case "B":
                valorNetoHora = cantidadHoras * 1000;
                break;
            default:
                return -1;
        }

        if (cantidadHoras > 3) {
            valorAdicion = (cantidadHoras - 3) * 2000;
        }
        else if(cantidadHoras <= 0){
            return -1;
        }

        return valorNetoHora + valorAdicion;
    }


    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularDescuento que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando la si es estudiante o no
            - Un entero represenatando la cantidad de horas
        * Retorna:
            - Un entero representando el valor del descuento
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    public static int calcularDescuento(int valorTotalHoras, int esEstudiante, int cantidadHoras){
        
        int valorDescuento = 0;

        if(cantidadHoras > 4){
            if (esEstudiante == 1){
                valorDescuento = (int)((float)valorTotalHoras * 0.35f);
            }
            else if(esEstudiante == 1){
                valorDescuento = (int)((float)valorTotalHoras * 0.30f);
            }
            else{
                return -1;
            }
        }
        
        return valorDescuento;
    }


    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularFactura que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando el valor del descuento
        * Retorna:
            - Un entero representando el valor del total de la factura incluyendo el iva
    */
    //------------------------------------------------------------------
    public static int calcularFactura(int valorTotal, int valorDescuento){
        return (int)((valorTotal + valorDescuento) * 1.19f);
    }


    //------------------------------------------------------------------
}
